name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Create settings.xml from the GitHub secret for publish
    - name: Create settings.xml for publish
      run: |
        cat <<EOF > $GITHUB_WORKSPACE/settings.xml
        <settings>
          <servers>
            <server>
              <id>colddev-repo</id>
              <username>padrewin</username>
              <password>${{ secrets.COLDDEV_REPO }}</password>
            </server>
          </servers>
        </settings>
        EOF

    # Build the project using Maven
    - name: Build with Maven
      run: mvn -B package -s $GITHUB_WORKSPACE/settings.xml --file pom.xml

    # Deploy the package to GitHub Packages using Maven
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -e -X
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
